name: mahesh_langote_advanced_notes_app
description: Advanced Notes Application with Flutter

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.9.2
  provider: ^6.1.2
  get_it: ^7.7.0
  reactive_forms: ^16.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0  
  uuid: ^4.4.2
  rxdart: ^0.28.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  auto_route_generator: ^7.3.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true